index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]
    
contact:
    path: /contact
    controller: App\Controller\DefaultController::contact
    methods: [GET]
    
one_post:
    path: /post/{id}
    controller: App\Controller\PostController::post
    requirements:
        id: '\d+'
    methods: [GET]
    
posts_by_category:
    path: /category/{categoryId}
    controller: App\Controller\PostController::postsByCategory
    requirements:
        categoryId: '\d+'
    methods: [GET]
  
greeflas_newsletter:
    resource: '@GreeflasNewsletterBundle/Resources/config/routes.yaml'
